import Descriptions from "@/componentes/Descriptions";
import Parent from "@/components/Parent";
import User from "@/components/User";
import Welcome from "@/components/Welcome";
import Head from "next/head";
import Form from "@/componentes/Form";
import Dog from "@/componentes/Dog";
import Counter from "@/componentes/Counter";
import Tasklist from "@/componentes/Tasklist/TaskList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World!</h1>
        <Welcome />
        {/* Importando componente User com uma expressão JSX */}
        <User />
        {/* Componente Parent incorporado com o componente filho */}
        <Parent />
        {/* Chamando componentes e passando a props */}
        <Descriptions name="Amanda" age={21} />
        {/* Usando a desestruturação para passar props */}
        <Dog name="Rex" breed="Pitbull" />
        {/* Contador */}
        <Counter />
        <Form />
        <br /><br />
        {/* Passando a lista de tarefa por Props */}
        <Tasklist 
          tasks={[
            {
              id:1,
              text: "Estudar React"
            },
            {
              id: 2,
              text: "Pagar boletos"
            },
            {
              id: 3,
              text: "Retirar o lixo"
            },
            {
              id: 4,
              text: "Lavar Roupa"
            }
          ]}
        />
        <br />
        <br />
        <br />
        
        
      </main>
    </>
  );
}
